image: maven:3.3.9-jdk-8-alpine

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  PRIDE_CONFIG_MAP: pride-pipelines-configmap
  DOCKER_PULL_SECRET: pride-gitlab-docker-secret
  IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  NAMESPACE: pride-pipelines-prod

cache:
  paths:
    - .m2/repository/
    - target/

#build:
#  variables:
#    DOCKER_AUTH_CONFIG: $docker_auth_json
#  stage: build
#  script:
#    - mvn $MAVEN_CLI_OPTS compile

.deploy_script:
  variables:
    DOCKER_AUTH_CONFIG: $docker_auth_json
  stage: deploy
  script:
    - apk add --update openssh-client bash openssl rsync gettext tzdata
    - eval $(ssh-agent -s)
    - echo $SSH_KEY | base64 -d | tr -d '\r' | ssh-add - > /dev/null
    - mkdir ~/.ssh
    - chmod 700 ~/.ssh
    - DEPLOY_SERVERS_ARRAY=(`echo $DEPLOY_SERVER | tr ',' ' '`)
    - for i in "${DEPLOY_SERVERS_ARRAY[@]}"; do ssh-keyscan $i >> ~/.ssh/known_hosts; chmod 600 ~/.ssh/*; done
    - export HOSTNAME_BCKUP=$HOSTNAME && export HOSTNAME='${HOSTNAME}'
    - envsubst < config/.application.yml > config/application.yml
    - export HOSTNAME=$HOSTNAME_BCKUP
    - (rm src/main/resources/*.properties || true)
    - cp scripts/runPipelineInJava.sh dummy.txt && envsubst '${SLACK_REPORT_URL}, ${SLACK_ERROR_REPORT_URL}, ${FILE_BEAT_PATH}' < dummy.txt > scripts/runPipelineInJava.sh
    - cp scripts/runPipelineInJava_SanityCheck.sh dummy.txt && envsubst '${SLACK_REPORT_URL}, ${SLACK_ERROR_REPORT_URL}, ${SLACK_APP_TOKEN}, ${sanity_check_report_slack_channel}' < dummy.txt > scripts/runPipelineInJava_SanityCheck.sh
    - cp scripts/projects_missing_annotations.sh dummy.txt && envsubst '${mongodb_machine_uri}, ${EXPORT_PATH}, ${MONGO_BIN_PATH}, ${NODE_PATH}, ${SLACK_APP_TOKEN}' < dummy.txt > scripts/projects_missing_annotations.sh
    - mvn $MAVEN_CLI_OPTS clean package -DskipTests
    - chmod -R 700 config && chmod 700 scripts/*.sh
    - DEPLOY_DIR=$(date +"%Y%m%d_%H%M%S")
    - mkdir $DEPLOY_DIR
    - cp -r target/*jar config scripts/* $DEPLOY_DIR/
    - cd $DEPLOY_DIR/ && jar_file=`ls *jar` && (ln -s $jar_file $JAR_FILE_LINK || true) && ls -al && cd ..
    - ssh $SERVER_USER@${DEPLOY_SERVERS_ARRAY[0]} "bash && mkdir -p $DEPLOY_PATH"
    - rsync -a $DEPLOY_DIR $SERVER_USER@$DEPLOY_SERVER:$DEPLOY_PATH/
    - ssh $SERVER_USER@$DEPLOY_SERVER "bash && cd $DEPLOY_PATH && ln -snf $DEPLOY_DIR current"

deploy_prod:
  environment: prod
  extends: .deploy_script
  #  only:
  #    - master
  when: manual

deploy_dev:
  environment: dev
  extends: .deploy_script
  #  only:
  #    - master
  when: manual